# Generated by Django 2.1.7 on 2019-03-19 08:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='questions',
            name='pub_date',
        ),
        migrations.AddField(
            model_name='questions',
            name='question_num',
            field=models.IntegerField(default=0),
        ),
    ]
