# Generated by Django 2.1.7 on 2019-03-19 08:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0002_auto_20190319_0856'),
    ]

    operations = [
        migrations.CreateModel(
            name='Answer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answer_options', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app1.Questions')),
            ],
        ),
    ]
