# Generated by Django 2.1.7 on 2019-03-19 09:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0003_answer'),
    ]

    operations = [
        migrations.RenameField(
            model_name='questions',
            old_name='question_num',
            new_name='question_number',
        ),
    ]
