# Generated by Django 2.1.7 on 2019-03-25 08:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0004_auto_20190319_0900'),
    ]

    operations = [
        migrations.CreateModel(
            name='api_example',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_field', models.CharField(max_length=10)),
                ('second_field', models.FloatField()),
            ],
        ),
    ]
